#### DKPaths.cmake ####

MESSAGE("Setting up DK Paths...")
GET_FILENAME_COMPONENT(DK2 ${CMAKE_SOURCE_DIR} ABSOLUTE)
DKSET(DKCMAKE ${DIGITALKNOB}/DKCMake)
DKSET(DKPLUGINS ${DIGITALKNOB}/DKPlugins)
DKSET(3RDPARTY ${DIGITALKNOB}/3rdParty)
DKSET(DKIMPORTS ${3RDPARTY}/_DKIMPORTS)
DKSET(DKDOWNLOAD ${DIGITALKNOB}/Download)
DKSET(DKWEB http://127.0.0.1)